baseURL: https://rop-srd.netlify.app/
languageCode: en-us
title: Realms of Peril SRD

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

menu:
  after:
    - name: Official Realms of Peril Website
      url: https://realmsofperil.webflow.io/
      weight: 10
